- name: Gateway config
  hosts: Routers
  gather_facts: false
  connection: local

  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: admin
    ansible_password: cisco
    ansible_become: yes
    ansible_become_method: enable
    ansible_python_interpreter: /usr/bin/python
    ansible_ssh_timeout: 3600
    ansible_command_timeout: 3600
  tasks:
    - name: Gateway config
      ansible.builtin.script: 
        cmd: /etc/ansible/playbook/script/Gateway_configuration.py
        executable: /usr/bin/python
      register: result
